import {Schema,model} from "mongoose";

const studentApplicationSchema=new Schema({
    student_name:{
        type:String
    },
    student_email:{
        type:String
    },
    student_roll_no:{
        type:Number,
        unique:true
    },
    father_name:{
        type:String
    },
    student_cellphone:{
        type:String
    },
    father_cellphone:{
        type:String
    },
    guardian_name:{
        type:String
    },
    guardian_cellphone:{
        type:String
    },
    cnic_no:{
        type:String
    },
    active_whatsapp_no:{
        type:String
    },
    postal_address:{
        type:String
    },
    permanent_address:{
        type:String
    },
    city:{
        type:String
    },
    province:{
        type:String
    },
    student_image:{
        type:String
    },
    cnic_image:{
        type:[String]
    },
    date_of_birth:{
        type:String
    },
    academic_year:{
        type:String
    },
    gender:{
        type:String
    },
    status:{
        type:String,
        enum:["accepted","pending","rejected"],
        default:"pending"
    },
    application_submit_date:{
        type:Date,
        default:Date.now,
        immutable:true
    },
    room_id:{
        type:Schema.Types.ObjectId,
        ref:"room"
    }
});
const studentApplicationModel=model("student_application",studentApplicationSchema);
export default studentApplicationModel;